const MimeType = new Map()

MimeType.set('.js', 'text/javascript')
MimeType.set('.json', 'text/json')
MimeType.set('.md', 'text/markdown')
MimeType.set('.woff', 'application/font-woff')
MimeType.set('.gif', 'image/gif')
MimeType.set('.jpeg', 'image/jpeg')
MimeType.set('.jpg', 'image/jpeg')
MimeType.set('.png', 'image/png')
MimeType.set('.svg', 'image/svg+xml')
MimeType.set('.webp', 'image/webp')
MimeType.set('.zip', 'application/zip')
MimeType.set('.mid', 'audio/midi')
MimeType.set('.mp4a', 'audio/mp4')
MimeType.set('.m4a', 'audio/mp4a-latm')
MimeType.set('.ogg', 'audio/ogg')
MimeType.set('.aac', 'audio/x-aac')
MimeType.set('.m3u', 'audio/x-mpegurl')
MimeType.set('.wma', 'audio/x-ms-wma')
MimeType.set('.ico', 'image/x-icon')
MimeType.set('.css', 'text/css')
MimeType.set('.csv', 'text/csv')
MimeType.set('.html', 'text/html')
MimeType.set('.txt', 'text/plain')
MimeType.set('.avi', 'video/x-msvideo')

export const getByMimeType = ext => {
  return MimeType.get('.' + ext) || ('application/' + ext)
}
·